### ISSUE TITLE
Getting Error After New Update

### ISSUE THREAD

**Issue by vishansh** [SVR666/search-bot#3]
Traceback (most recent call last):                                                             
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main                         
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)                           
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details                         
    return _get_module_details(pkg_main_name, error)                                           
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details                         
    __import__(pkg_name)                                                                       
  File "/home/vishal/test/search-bot/bot/__init__.py", line 19, in <module>                    
    load_dotenv('config.env')                                                                  
  File "/home/vishal/.local/lib/python3.6/site-packages/dotenv/main.py", line 312, in load_dote
nv                                                                                             
    return DotEnv(f, verbose=verbose, interpolate=interpolate, **kwargs).set_as_environment_var
iables(override=override)                                                                      
  File "/home/vishal/.local/lib/python3.6/site-packages/dotenv/main.py", line 106, in set_as_en
vironment_variables                                                                            
    os.environ[to_env(k)] = to_env(v)                                                          
  File "/usr/lib/python3.6/os.py", line 675, in __setitem__                                    
    self.putenv(key, value)                                                                    
ValueError: embedded null byte

**Comment by SVR666** [comment]
https://t.me/joinchat/NG6qaRTFYEdcKWpiMlZ4eg
join this grp
